version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3307/dena_paonaDB
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: dena_paonaDB
      MYSQL_USER: dena_paona
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 0110011001
networks:
  springapimysql-net: